version: "3"
services:
  db:
    image: postgres:latest
    container_name: "my_postgres"
    ports:
      - "54320:5432"
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - my_dbdata:/var/lib/postgresql/data
volumes:
  my_dbdata: